#!/bin/bash
# Obtaining the user system information like the hostname, the operating system,
# and how long the system has been running

HostName=$(hostname)
source /etc/os-release
UpTime=$(uptime)

# Obtaining the hardware information of the computer and its components like the CPU, Speed of CPU,
# RAM, Disk, and video

# Network information: Fully qualified domain name, Host IP, Default gateway, DNS server IP, interface, and its IP
FQDN=$(hostname -f)
HostIP=$(hostname -I)
DefaultGatewayIP=$(ip route | awk '/default/ { print $3 }')
DNSServerIPAddress=$(awk '/nameserver/ { print $2 }' /etc/resolv.conf)

InterfaceName=$(ip -o link show | awk -F': ' '{print $2}')
IPAddressOfSystem=$(ip -o -4 addr show | awk '{print $4}')


# System status information: Logged-in user, Processor count, Load Average, Memory Allocation
CurrentUser=$(who | cut -d" " -f1 | sort | uniq | tr '\n' ',' | sed 's/,$//')
ProcessorCount=$(ps -ef | wc -l)
AverageLoad=$(uptime | awk -F'average:' '{print $2}' | tr -d ',')
MemoryAllocation=$(free -h | awk '/Mem:/ {print $3}')

# Printing the system report
echo "
System report has been generated by user named $USER on $(date)

**** System Information *****
Hostname is $HostName
Operating System running on system is $PRETTY_NAME
Uptime of System is $UpTime

**** Hardware Information ****

**** Network Information ****
FQDN for the system is $FQDN
Host IP Address is $HostIP
Default Gateway of System is $DefaultGatewayIP
IP Address of DNS Server is $DNSServerIPAddress

Interface we have is $InterfaceName
IP Address is $IPAddressOfSystem

**** System Status *****
User currently using the system is $CurrentUser
Processor count is $ProcessorCount
Load Average is $AverageLoad
Memory Allocation is $MemoryAllocation
"
